application: gdg-larsjangaard
version: beta
runtime: python27
api_version: 1
default_expiration: 1h
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /rest/css
  static_dir: rest/css

- url: /rest/js
  static_dir: rest/js

- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.3"

skip_files:
- ^app\.yaml$
- ^index\.yaml$
- ^.*\#$
- ^.*~$
- ^.*\.py[co]$
- ^(.*/)?\.
- ^.*\.bak$
- ^.*\.orig$
